# Generated by Django 4.0.4 on 2022-11-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_hardoim_yeydigan_foodlari',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_hardoim_yeydigan_foodlari',
            name='vazn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_hardoim_yeydigan_foodlari',
            name='yosh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
