# Generated by Django 4.0.4 on 2022-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0003_user_hardoim_yeydigan_foodlari_jins'),
    ]

    operations = [
        migrations.CreateModel(
            name='calories_MET_tech_details_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('met', models.CharField(default='0', max_length=100)),
                ('major_heading', models.CharField(default='None', max_length=200)),
                ('exercise_definition', models.CharField(default='None', max_length=1000)),
            ],
        ),
    ]
