# Generated by Django 4.0.4 on 2022-11-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0004_calories_met_tech_details_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_hardoim_yeydigan_foodlari',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user_hardoim_yeydigan_foodlari',
            name='jins',
        ),
        migrations.RemoveField(
            model_name='user_hardoim_yeydigan_foodlari',
            name='yosh',
        ),
    ]
