# Generated by Django 4.0.4 on 2022-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0005_remove_user_hardoim_yeydigan_foodlari_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories_met_tech_details_add',
            name='met',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=34, null=True),
        ),
    ]
